<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Solve Puzzle</name>
   <tag></tag>
   <elementGuidId>4e04c442-babd-4967-b80c-efb7ad28e9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='home_children_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home_children_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2490ff16-7c35-4862-8aa7-53cd1858387f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>descriptionVerify</value>
      <webElementGuid>5c695978-e1f5-41b0-8fb8-e0e88c62fff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_children_button</value>
      <webElementGuid>5a595d48-adfa-4760-b0dc-162338063949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdnxRM bdpiRp sc-kEqXSa escriG</value>
      <webElementGuid>8f98aff0-cf2e-4557-a424-1eafb32429b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solve Puzzle</value>
      <webElementGuid>a5cfe52b-ac33-4516-aa4a-91a58085df17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_children_button&quot;)</value>
      <webElementGuid>45a08ab7-6b20-42d0-b04d-a1a42b233016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Authentication required/iframe_Audio challenge is available below. _e329ec</value>
      <webElementGuid>727d7acf-3665-4d2f-9c93-220176e49647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='home_children_button']</value>
      <webElementGuid>1207de89-2929-4d07-834b-8ae61a456f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/button</value>
      <webElementGuid>0c8d623f-c4d0-4356-92aa-f5480563ea8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us protect your account'])[1]/following::button[1]</value>
      <webElementGuid>76e11596-1ac2-403e-8c0f-b937c6073c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual challenge.Audio challenge is available below. Compatible with screen reader software.'])[1]/preceding::button[1]</value>
      <webElementGuid>c31f0645-a7dc-49d9-b6c4-fef22d0f70ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'home_children_button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>f2a88949-3835-4aed-8001-73e9731c8514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solve Puzzle']/parent::*</value>
      <webElementGuid>466dfbed-6c90-4cd0-a8cd-d3a3ebfc3241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>63aba800-01cb-410e-a6f9-20b6fb578c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'home_children_button' and (text() = 'Solve Puzzle' or . = 'Solve Puzzle')]</value>
      <webElementGuid>546ed410-e862-4997-a6b5-7ac4244964f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
