<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fc-iframe-wrap, , ))_f_d38848</name>
   <tag></tag>
   <elementGuidId>3fa86cbf-dd01-41fc-9775-557ef4dc47a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fc-iframe-wrap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-iframe-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7eff5aec-e5a8-495f-89f6-7b0a9421da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7e935cd-1e07-4ea6-b325-3f7317324a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>468f1018-cb86-4022-9338-1b6afad66a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-iframe-wrap</value>
      <webElementGuid>8e736f83-d191-42c1-8785-2cec64905a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-iframe-wrap</value>
      <webElementGuid>704d4e66-5a80-4c54-a455-990be178f320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://client-api.arkoselabs.com/fc/gc/?token=436290b810652413.7581141904&amp;r=ap-southeast-1&amp;metabgclr=%23ffffff&amp;maintxtclr=%231B1B1B&amp;mainbgclr=%23ffffff&amp;guitextcolor=%23747474&amp;metaiconclr=%230073cf&amp;meta_height=288&amp;meta_width=302&amp;meta=9&amp;lang=en&amp;pk=2F1CD804-FE45-F12B-9723-240962EBA6F8&amp;dc=1&amp;at=40&amp;ht=1&amp;atp=2&amp;cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc&amp;lurl=https%3A%2F%2Faudio-ap-southeast-1.arkoselabs.com&amp;surl=https%3A%2F%2Fclient-api.arkoselabs.com&amp;smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager</value>
      <webElementGuid>369898f8-2989-48bf-87d2-f51ed58c1ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-iframe-wrap&quot;)</value>
      <webElementGuid>d25dcdad-d2c9-49df-9313-af3236fd987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Authentication required/iframe_Z6wXJz-G-6vcu3I0ZoM_B show active inline</value>
      <webElementGuid>c057960f-5e1a-46d0-8919-6837d607c69a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fc-iframe-wrap']</value>
      <webElementGuid>426f9bbf-6494-436d-9943-45123bd01535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FunCaptcha']/iframe</value>
      <webElementGuid>451eb2c6-dcd0-4ba3-988c-c40410d66995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f5829a09-b0fd-424a-9ea1-9ae3f6da6133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fc-iframe-wrap' and @src = 'https://client-api.arkoselabs.com/fc/gc/?token=436290b810652413.7581141904&amp;r=ap-southeast-1&amp;metabgclr=%23ffffff&amp;maintxtclr=%231B1B1B&amp;mainbgclr=%23ffffff&amp;guitextcolor=%23747474&amp;metaiconclr=%230073cf&amp;meta_height=288&amp;meta_width=302&amp;meta=9&amp;lang=en&amp;pk=2F1CD804-FE45-F12B-9723-240962EBA6F8&amp;dc=1&amp;at=40&amp;ht=1&amp;atp=2&amp;cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc&amp;lurl=https%3A%2F%2Faudio-ap-southeast-1.arkoselabs.com&amp;surl=https%3A%2F%2Fclient-api.arkoselabs.com&amp;smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager']</value>
      <webElementGuid>d75353c6-c12c-4a07-b0cc-37cf1a4e8115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
