<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Audio challenge is available below. _e329ec</name>
   <tag></tag>
   <elementGuidId>473611e9-6430-4b24-b097-f5459832e9d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='CaptchaFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CaptchaFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>09f35b28-80cf-4b51-ba06-8831f2b0e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrapper</value>
      <webElementGuid>07956d2a-8d3e-424a-a318-c0f65f72fdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CaptchaFrame</value>
      <webElementGuid>4fa28f9f-c05e-42c1-b66d-4b56841913df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Visual challenge</value>
      <webElementGuid>c2e15edf-33ea-495a-a648-6011b2ae2218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>bb03cf77-daf1-4c43-ad6a-8b8d83ca0108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>horizontalscrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>36ea344d-679a-4407-8cab-1839ec52ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>verticalscrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ead90eae-2912-4d3e-9604-977817a89006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3a760b5f-9296-46c3-abc7-73fcd2a6734c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CaptchaFrame&quot;)</value>
      <webElementGuid>baa8b770-4e27-4607-8ede-ff415b42b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Authentication required/iframe_concat(id(, , fc-iframe-wrap, , ))_f_d38848</value>
      <webElementGuid>f6ecbc3a-6ce9-41ee-ad1c-513ffb859633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='CaptchaFrame']</value>
      <webElementGuid>1143a016-9159-48c7-87fc-d5123be470b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctn-1']/iframe</value>
      <webElementGuid>f6e7ea90-6057-4e0c-a61e-15110cacf894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio challenge is available below. Compatible with screen reader software.'])[1]/following::iframe[1]</value>
      <webElementGuid>1b466f36-e9f1-4779-b446-7d973fed5f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Please prove you', &quot;'&quot;, 're not a spammer by doing this quick activity!')])[1]/preceding::iframe[2]</value>
      <webElementGuid>db87e29e-83d9-471c-b655-63073761592d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solve Puzzle'])[1]/preceding::iframe[2]</value>
      <webElementGuid>c63f8a3e-846b-49f2-afb4-8138ec7e42df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cc70391d-2932-455f-ad03-59eed381a49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'CaptchaFrame' and @title = 'Visual challenge' and @src = 'about:blank']</value>
      <webElementGuid>a27d44f8-2dbf-4394-8dc0-20c28627d4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
