<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sorry, something went wrong on our e_8051c0</name>
   <tag></tag>
   <elementGuidId>f2ab4279-35f8-4178-a886-6f544bf0ae89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cvf-arkose-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cvf-arkose-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41b045a4-fdf4-4ae6-8914-3ef314fcb400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvf-arkose-frame</value>
      <webElementGuid>9c9ce2ff-dd77-426a-b023-4258c67d212e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cvf-captcha-iframe</value>
      <webElementGuid>1631f26c-30bc-4046-a132-1eecbd714771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4aacbf0f-b1a5-459a-9a5e-85a32dd353fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6354a9bd-2482-4649-aa19-f06ecd856afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-forms</value>
      <webElementGuid>7f950032-c7b6-486b-aed0-98eafd6f18ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://iframe.arkoselabs.com/2F1CD804-FE45-F12B-9723-240962EBA6F8/index.html?data=VRnVHO2uhw7Gd87H14R7Sg%3D%3D.BHvMXEabozdhmR9Yy8iBLVxzBOTDAZnW3ycxSYX4%2Fk+3jmZ3PgzI9RqzNByANMbTAubyDM55RCMTRS2OPfTRRmTkRH3pxVxskjZ%2FSuH8DDDW+dIhH0t%2FZyNWIiS8kNjpwVdyDg3FlU927QoP03wK0a1dF54%3D&amp;mkt=en-US</value>
      <webElementGuid>48b4f79e-43b2-4f95-8a97-c08cf0f89f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-arkose-frame&quot;)</value>
      <webElementGuid>1165c2fc-1cd3-43f0-8a75-f8f1051b32a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cvf-arkose-frame']</value>
      <webElementGuid>abf36ed0-70d3-4297-8a35-44db94699d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-arkose-js-elements']/iframe</value>
      <webElementGuid>a9f5bdb1-f622-488b-a392-c2a96cf4d72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>45e56813-2164-433c-9833-3942676c8c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cvf-arkose-frame' and @src = 'https://iframe.arkoselabs.com/2F1CD804-FE45-F12B-9723-240962EBA6F8/index.html?data=VRnVHO2uhw7Gd87H14R7Sg%3D%3D.BHvMXEabozdhmR9Yy8iBLVxzBOTDAZnW3ycxSYX4%2Fk+3jmZ3PgzI9RqzNByANMbTAubyDM55RCMTRS2OPfTRRmTkRH3pxVxskjZ%2FSuH8DDDW+dIhH0t%2FZyNWIiS8kNjpwVdyDg3FlU927QoP03wK0a1dF54%3D&amp;mkt=en-US']</value>
      <webElementGuid>d8801b70-bbdd-4569-82ca-9f425599faa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
